name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: |
          uv sync
      - name: Install Playwright Chromium
        run: |
          uv run playwright install chromium
      - name: Run tests
        run: |
          uv run pytest -q


